### ISSUE TITLE
[Bug]生成的Entity表中字段名命名格式不正确

### ISSUE THREAD

**Issue by Gn3po4g** [xuejmnet/easy-query-plugin#4]
如题。插件生成的字段命名格式为全小写。

**Comment by xuejmnet** [comment]
@Gn3po4g 表到entity的话对于java而言java的字段|属性最标准的就是小驼峰吧

**Comment by Gn3po4g** [comment]
![图片](https://github.com/user-attachments/assets/3d50f32b-fe90-4a0c-8900-c0af05da7dea)

不知道为什么我这里通过插件生成的类的字段都是全小写的

![图片](https://github.com/user-attachments/assets/3da6f20d-a441-4874-ab0d-e05ff7ecc3b3)

**Comment by xuejmnet** [comment]
数据库配置是忽略大小写?
导致idea读取不到原始信息吗

**Comment by xuejmnet** [comment]
如果真的是插件的bug可以尝试用mybatis的生成器网上应该很多的可以拿一个试试看反正生成的class两边都能用

**Comment by Gn3po4g** [comment]
> <img alt="image" width="923" src="https://private-user-images.githubusercontent.com/18061232/379183492-d2fc1ad9-f416-4b5f-b2de-507b90db814c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzM5NTgsIm5iZiI6MTcyOTY3MzY1OCwicGF0aCI6Ii8xODA2MTIzMi8zNzkxODM0OTItZDJmYzFhZDktZjQxNi00YjVmLWIyZGUtNTA3YjkwZGI4MTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4NTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZGYwYTMyOWY0OTdmZGY1NWQ2MTI1ZGVjZTJkMzBhNmIwZjM5MTI0MTA3MDE3NzI1YTRhZGNhNDZhNzE5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zdQtRsQgJyjyBGMOBeNj9qvpfsO0Lqxngq6rHF3DQlg">

这个是生成的。数据库lower_case_table_names的值为1。

**Comment by Gn3po4g** [comment]
插件生成的字段格式是按照数据库格式来的吗？

**Comment by xuejmnet** [comment]
@Gn3po4g 
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/31558872-bcee-4744-b2f5-95821a40dd2c">
我看到默认是没有的应该是你自己写的吧如果是生成的那么你可以改成和模版里面一样的即可,顺便问下是什么数据库

**Comment by xuejmnet** [comment]
@Gn3po4g 实在不好意思我看了确实是代码问题你可以选择修改一下使用`column.name`而不是`column.fieldName`
<img width="985" alt="image" src="https://github.com/user-attachments/assets/5543dc53-f08e-4924-bed5-dba2fe17b5aa">

**Comment by Gn3po4g** [comment]
> @Gn3po4g 实在不好意思我看了确实是代码问题你可以选择修改一下使用`column.name`而不是`column.fieldName` <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/18061232/379189879-5543dc53-f08e-4924-bed5-dba2fe17b5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzQ5MjcsIm5iZiI6MTcyOTY3NDYyNywicGF0aCI6Ii8xODA2MTIzMi8zNzkxODk4NzktNTU0M2RjNTMtZjA4ZS00OTI0LWJlZDUtZGJhMmZlMTdiNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA5MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NGE3OGEzMjE2ZGQyMGI5MmEwOGUxMzBmZDVmMzA5OTRhMmM3YjcxZjYzMDdmZTNmNThlZjdlOWQxNGIxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T4YI001TN6XhgCSxsSEN9Ajn1SK5qYaprGx8_jmkXYE">

好的，不过模板我没有改过，默认是有value的
![图片](https://github.com/user-attachments/assets/1a6c712e-f3f0-4e3c-a3c6-f167e39978bd)
win11系统，插件0.0.64版本，mysql数据库。

**Comment by xuejmnet** [comment]
@Gn3po4g 我的意思就是你改成name就好了别用fieldName
<img width="1682" alt="image" src="https://github.com/user-attachments/assets/20eed2ff-390e-454a-82c7-da790ac47a49">
fieldName确实被toLower了

**Comment by Gn3po4g** [comment]
嗯，已经改好了。
如果fieldName为小驼峰形式的话，感觉模板可以添加一行@Column(value = "数据库列名")

**Comment by xuejmnet** [comment]
ok到时候修复一下

**Comment by Gn3po4g** [comment]
问题原因应该是eq默认是将字段名映射为snake_case。但是就像我上面展示的，数据库中字段名为小驼峰形式，所以会导致将整个字段名识别为一个单词吧

**Comment by Gn3po4g** [comment]
比如
![图片](https://github.com/user-attachments/assets/5560a813-d789-4724-8c78-eafeefb5e439)
不加任何注解，运行会报错
![图片](https://github.com/user-attachments/assets/d66a3f33-8ed1-4aaf-8920-4cb54f62dc33)

**Comment by xuejmnet** [comment]
@Gn3po4g 您这个是运行时的问题可以参考eq的配置和插件无关,
<img width="2070" alt="image" src="https://github.com/user-attachments/assets/e820296b-8d53-4f22-961a-705077f1f2c6">

http://www.easy-query.com/easy-query-doc/config/config-option.html

**Comment by Gn3po4g** [comment]
这样啊😂，那插件的命名规则不知道是怎样的，也应该有个设置或者使用eq的配置吧

**Comment by xuejmnet** [comment]
@Gn3po4g 插件只是为了提高使用体验之前是因为有全大写的比如USER_NAME然后需要转换成userName,所以才先将列转成全小写然后将下划线后的字母转成大写。。。。你数据库的列名刚好是没有下划线的那种小驼峰所以修改一下模板也可以做到插件生成实体,配置默认是驼峰转下划线，你设置为default即可就是表示java实体和数据库是两边一致的

**Comment by xuejmnet** [comment]
当然你也可以在@Column里面设置具体的列名但是我觉得这样就会导致换库的时候出现问题因为你可能换到别的库他的数据库规范可能是小驼峰所以不建议在@Column里面将列名写死不过如果你没有换库的要求那么可以写死

**Comment by Gn3po4g** [comment]
好的。那我关闭议题了。希望插件后续可添加这方面的可配置项吧♥️
