### ISSUE TITLE
kotlin项目gradle + ksp项目插件生成的proxy位置不对

### ISSUE THREAD

**Issue by hzychen** [xuejmnet/easy-query-plugin#5]
期望生成路径在build/generated/ksp/main/java

**Comment by Gn3po4g** [comment]
gradle中遇到了类似的问题。
EntityQueryImplement实现了ProxyEntityAvailable接口，但是生成目录没有创建Proxy类，需要手动构建一次。
插件版本0.0.65，sql-processor版本2.0.98

**Comment by xuejmnet** [comment]
> gradle中遇到了类似的问题。 EntityQueryImplement实现了ProxyEntityAvailable接口，但是生成目录没有创建Proxy类，需要手动构建一次。 插件版本0.0.65，sql-processor版本2.0.98

已经了解了再修复了可以加群到时候我会先发群里,毕竟idea发插件需要审核

**Comment by xuejmnet** [comment]
@hzychen @Gn3po4g 0.0.67进群或者等1-2天jb审核市场下载，进群可以下载离线版

**Comment by xuejmnet** [comment]
@Gn3po4g 等1-2天0.0.70已经修复或者进群即可

**Comment by xuejmnet** [comment]
@Gn3po4g build目录下0.0.67会生成多份额外的文件0.0.70不会
