### ISSUE TITLE
TableGenerate失败

### ISSUE THREAD

**Issue by wugegezuishuai** [xuejmnet/easy-query-plugin#6]
随便删除一个项目中的文件，idea会报错
![image](https://github.com/user-attachments/assets/c205f7a0-3c97-4b89-865e-647b2b8f9193)
然后执行TableGenerate会提示生成文件失败。需要重启idea才行

**Comment by xuejmnet** [comment]
[已修复](https://github.com/xuejmnet/easy-query-plugin/pull/11)
